on: [push, workflow_dispatch]
name: .NET breakage reproducer

env:
    DOTNET_INSTALL_DIR: ".dotnet"
    DOTNET_ROOT: ".dotnet"
    DOTNET_HOST_PATH: ".dotnet"

jobs:
  dotnet-info:
    name: Run `dotnet --info`
    runs-on: windows-latest
    steps:
      - name: Install .NET 7.0.x for kicks
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            6.0.x
            8.0.x

      - name: Checkout
        uses: actions/checkout@v4

      - name: Run `dotnet --info`
        run: dotnet --info

  dotnet-workload-search:
    name: Run `dotnet workload search`
    runs-on: windows-latest
    steps:
      - name: Install .NET 7.0.x for kicks
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            6.0.x
            8.0.x
        env:
            DOTNET_INSTALL_DIR: ".dotnet"

      - name: Checkout
        uses: actions/checkout@v4

      - name: Run `dotnet workload search`
        run: dotnet workload search
