on: [push, workflow_dispatch]
name: .NET breakage reproducer


jobs:
  dotnet-info:
    name: Run `dotnet --info`
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run `dotnet --info`
        run: dotnet --info
        working-directory: DotnetBreakageReproducer

  dotnet-workload-search:
    name: Run `dotnet workload search`
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run `dotnet workload search`
        run: dotnet workload search
        working-directory: DotnetBreakageReproducer
