on: [push, workflow_dispatch]
name: .NET breakage reproducer


jobs:
  dotnet-info:
    name: Run `dotnet --info`
    runs-on: windows-latest
    env:
      DOTNET_INSTALL_DIR: "./dotnet"
    steps:
      - name: Install .NET 8.0.x to external directory
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      - name: Checkout
        uses: actions/checkout@v4

      - name: Run `dotnet --info`
        run: dotnet --info

  dotnet-workload-search:
    name: Run `dotnet workload search`
    runs-on: windows-latest
    env:
      DOTNET_INSTALL_DIR: "./dotnet"
    steps:
      - name: Install .NET 8.0.x to external directory
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      - name: Checkout
        uses: actions/checkout@v4

      - name: Run `dotnet workload search`
        run: dotnet workload search
